# Site settings
title: Dmitry's Trefilov blog
email: 
description: ""
baseurl: ""
url: "http://dmitofclubs.github.io"
twitter_username: ee_rookkkkkkkk
github_username:  dmitofclubs

## excerpt
excerpt_separator: <!--more-->

## license
license: CC-BY-NC-4.0 # "CC-BY-4.0", "CC-BY-SA-4.0", "CC-BY-NC-4.0", "CC-BY-ND-4.0"

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
